sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: eb0lxXMs92423DyP34ETe8laltJbAn+GRZbNcg6+fiecYZamUAvAAQPHoxRVGMCCNtzeEBlTQIhBqT11EZLo9FqFVvndquDtBauSO84gopfOxmvPKxNjqMJ3cZsSsWNUgbz3Fqstqn/xUt16XGwX0+1MMa0DzJDLPwHiNDldZcjSncI31sSXeB23aHLO/mYPX0UMqV+1ZIlRNtx2mij9pDLooIqSaQA9Wx5VBq9+aZVYXuErSEZP0guxz6cU6zV5J4UPuRRnIIrjndd4JCzMkezx0nrtMIU5/TXC4/n7SpjUWzsd5N/H1bRFuNseMeb/FKR3B0Q0oDO25CPG4vR+pVLovxxLDjd+mCfB1cY489h7WpBO74mJbSQbIF3avXdtXQknWfU/gTvBmmezPvF+cZHTYAoItpi3kWGOv/YEFsnvx7sSU06G/XDjpd6nv5hdZwkdFEaL36u8hummmbZufs7SYARZEpOWXc1PTMwdBwy+bmVQ409yIsfQh5ywdrz+cP2G+4olluzw+99YnyRMcMM13+zzCQCS2zXDNNnAvShka4cmEji5F2d2xIgT0044btL3LO2p5m3jkDCE4p8q1BlRogZWMFHuqKZgvvoZ4kFgtZ/SD7xBF4L3ZWiXWCpYdNMQiyPZwy/9JXFVKTf1uLwJ73rjwLLUDE+fHITqIOU=
  - secure: rNgqVkYi9dEutF78trb+z9n+hf5jHwV0+RotAeBZ3sdogCToWKQ7L1mulF4ZoDaqvfoYhiOPPfSZLBx3+kagwhEDymovKC5C0CoUHoX6WRDic26d6cb8Chw0Dnxwp7DS4hYWMGPeKyQcFrWhm3yFN3ZrHLHSW7SiwJre690nKIL+CX6Eva1M8V3txBg3+2aC18Kpaum/UBYPazgIITCxI5jw8lZQ6ULNE2i3z+dsG5jc9s3yNNJByHeREu8pGMTGUDjKqFFhzVMsqptU/kVJpzcgAxS0WfUX6GuT5Y5XDA+n+ru9d01G1nLOKrNJLnvs8EMS94abSW7IqQp22EUbG8nprETE6uZAlrUrQGY5xtrcrlRaJQZ8vcO6JVGk0eazM3IDm4ezOQFhyReqkN5ZAwiMPhoUaI3+Cc5mEDUqvSTyxdiFeBiIi0zinxb9aNj+J3uw65aCWgC332QUFDxkw3R19M3Q4JhJ/Al2VjStwxx2yMHeDxKG5tRUqMxGVqBVEdulINEzZAYP/ZqAjkc3bhkBAzwrCYIUFwYHUqiW1+YeQ+wrLAY6czqtKs5aIp5gPmLHpy/AWw35zwA9osCm978kVkmLBgtE/2BZaUupc2L98o6Vv8ETlZIZcB7pgAciNx+xNBBY3ULKoTcLHK6kEEX9qL6or46ITM5T1lILLyc=
