name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install HTTPIE
        run: apt-get install httpie
      - name: Build all the containers
        run: ./travis-ci.sh
